# Site settings
title: CoderPro
header-img: img/home-bg.jpg
email: kamiljamroz@outlook.com
description: "CoderPro!"
baseurl: "/CoderPro"
url: "http://CoderPro2xpl.com"
twitter_username: NergyDesign
github_username:  MrozoPL
facebook_username:  Kamil Jamróz

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

